### ISSUE TITLE
Feedback, 1st round

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/apidocs#1]
Hi, some thoughts questions regarding your API draft:
- On POST:/collections do we require a collection with minted PID or do we mint it if necessary?
- If so, will the PID field in a collection be optional then?
- For GET/POST/DELETE:/collections/{id}/items I will suggest a Cursor return type to enable iterating/navigating the result set
- Do we have a mechanism to retrieve actual source data? Somehow we should convey the location of an item or a service to find it. Either the Item type could provide that information or a separate path.
- I don't think the distinction between contains and matches is very clear and/or necessary. Is contain a query for an exact match and matches an AND/OR query? In either case I could see them on a single path with query parameters to control the precise interpretation of the query.
- I also think the return values could be made more consistent by using a CURSOR type.
- On a more general note, have we talked about the risk of cyclic graphs resulting from recursiveness (collections of collections)?

**Comment by balmas** [comment]
re POST minting a new collection PID -- I think PID assigning should be delegated, e.g. to the PIT API, and not part of the responsibilities of the Collections API, but others may not agree here.

re CURSOR return type, yes that makes sense

re retrieving source data, yes Item type should provide the URL to the item data. I'll add that.

re contains vs matches -- can't remember what I was thinking about the distinction there, so it is likely not necessary :)

**Comment by balmas** [comment]
To see latest version with these changes, launch http://rdacollectionswg.github.io/apidocs/# and specify path to swagger file as https://raw.githubusercontent.com/RDACollectionsWG/apidocs/operations/swagger.json

**Comment by TobiasWeigel** [comment]
- You explained much earlier how accesstypes mean sth like "public", "mixed", "private". I do not understand how the creation of a new accesstype via POST would actually work - in my understanding, the accesstypes are predefined by the server/repository. Also - would it make sense to you to merge accesstypes, model types and possibly other stuff into a "server's capabilities" call?
- Why is /collections/{id}/matches a POST operation? POST should result in some creation action. I think that matches should be a GET operation. This operation also needs more parameters.

**Comment by balmas** [comment]
1. Yes, I belive we need to completely remodel the accesstypes/modeltypes api calls in view of the capabilities discussion.
2. the reason I had /collections/{id}/matches as a POST operation (I think) was under the assumption that the caller might want to POST a not yet persistently identified item which contained the properties to be matched

**Comment by fbaumgardt** [comment]
I can answer the second question — you'd post a valid serialization of an object and thereby ask if the4 collection identified by the id contains item(s) with matching properties. This would presumably work similarly to MongoDB’s db.collection.find() or .aggregate($match). Hence the POST rather than GET.

**Comment by TobiasWeigel** [comment]
1. I see and agree. Maybe we should also distinguish between the server's capabilities and individual collections' capabilities.
2. OK, thank you for the clarification - you are describing a fictional complex item to match against. This also means you are using the POST like a complex GET request, which is odd but covered by the standards and best practice (e.g. for web forms).
