### ISSUE TITLE
POST a new collection should return the newly created collection

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/apidocs#10]
If the service is minting identifiers, it will be necessary to return the newly added collection so the clients can find out what id was assigned. But it is potentially problematic for implementations which are asynchronous.

**Comment by balmas** [comment]
we will change POST memberitem response too for consistency

**Comment by fbaumgardt** [comment]
If I'm not mistaken this has been in place all along, i.e. https://github.com/RDACollectionsWG/apidocs/blob/master/swagger.yaml#L103 and https://github.com/RDACollectionsWG/apidocs/blob/master/swagger.yaml#L536. It will need to be updated to reflect the change to creating multiple objects in a single call.
