### ISSUE TITLE
Do we need url parameters for pagination?

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/apidocs#12]
While setting out to implement pagination I couldn't find any actionable specs on this.

**Comment by balmas** [comment]
Most of the requests that return sets (e.g. see the ops requests and members) have a cursor parameter for that, but it looks like it got dropped off of the main collections request.

**Comment by fbaumgardt** [comment]
Yep, found it. I only checked GET /collections.

Did we have a format for the cursor string in mind or left it to the implementation? Obvious examples would be uuids for opaque and \<stepsize\>_\<page\> for transparent navigation.

**Comment by fbaumgardt** [comment]
Sorry, markdown ate something in the last message.

[...] \<stepsize\>_\<page\> for transparent navigation [...]

**Comment by fbaumgardt** [comment]
Nevermind, just check it on github.com, I fixed it there. Operating on just half a mug of coffee here. 🙄

**Comment by balmas** [comment]
Note from 13-June-17 call: documentation should include note that if you implementation pagination you must enforce a defined sequence.

**Comment by balmas** [comment]
the way this was implemented so far was:

- a paginated response returns a prev_cursor and next_cursor field
- to request paginated results, you pass in the value of that field to request the next/prev page

**Comment by balmas** [comment]
recommend use of etag to check whether collection has changed in the interim?

**Comment by balmas** [comment]
we should add this to collections.
