### ISSUE TITLE
Improve readability for POST /collections data model

### ISSUE THREAD

**Issue by fbaumgardt** [RDACollectionsWG/apidocs#17]
- [ ] Add further description in *Implementation Notes*
- [ ] See if it's possible to replace `Inline Model 1` with `CollectionObject`

**Comment by balmas** [comment]
I believe it is correctly represented in the spec, and it was just a problem with the swagger-ui. I've updated the swagger-ui code in the gh-pages branch of the repo, and it all looks okay to me now.
