### ISSUE TITLE
DC collections ontology mapping

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/apidocs#5]
Feedback from Juha Hakala:

the Dublin Core collections application profile has a useful data model for collections. See 
http://dublincore.org/groups/collections/collection-application-profile/

@fbaumgardt is looking at this

**Comment by fbaumgardt** [comment]
Mappings are here: https://github.com/RDACollectionsWG/apidocs/wiki/Mapping-properties-to-LOD-URIs

**Comment by balmas** [comment]
Description should be an object not a String...

**Comment by balmas** [comment]
Ulrich is examining implications of using the DTR to assign identifiers for some or all of these

**Comment by balmas** [comment]
from Ulrich:
[DTR-specifications.txt](https://github.com/RDACollectionsWG/apidocs/files/1139698/DTR-specifications.txt)
