### ISSUE TITLE
DELETE return value

### ISSUE THREAD

**Issue by balmas** [RDACollectionsWG/apidocs#9]
Per discussion in #2, DELETE on a property of a member should return the updated MemberItem

**Comment by balmas** [comment]
@fbaumgardt one possible problem I see with this is that asyncrhonous requests might not be able to return this immediately. That might be why I left these return values blank in the first place....

**Comment by balmas** [comment]
Per 13-June-2017 call agreed upon return success/failure only

**Comment by fbaumgardt** [comment]
No action needed.
